version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout # not sure why this isn't a default...
      - run: ls
      - run: npm install -g htmlhint
      - run: htmlhint --config htmlhint.conf index.xhtml
